version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - echo "Installing Something"
  pre_build:
    commands:
      - npm run build
      - echo "We are in build Phase"
  build:
    commands:
      - echo "We are in build block"
      - echo "We will run some tests"
  post_build:
    commands:
      - echo "We are in a post build phase"
